# filepath: helm-argocd-app/templates/application.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ .Values.metadata.name }}
  namespace: {{ .Values.metadata.namespace }}
spec:
  project: {{ .Values.spec.project }}
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    path: {{ .Values.spec.source.path }}
    targetRevision: {{ .Values.spec.source.targetRevision }}
    helm:
      valueFiles:
      {{- range .Values.spec.source.helm.valueFiles }}
        - {{ . }}
      {{- end }}
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: {{ .Values.spec.destination.namespace }}
  syncPolicy:
    automated:
      selfHeal: {{ .Values.spec.syncPolicy.automated.selfHeal }}
      prune: {{ .Values.spec.syncPolicy.automated.prune }}